name: mad2_login
description: Login for JagHub.

version: 1.0.3

false_secrets:
  - /android/app/google-services.json
  - /ios/Runner/GoogleService-Info.plist
  - /lib/firebase_options.dart
  - /macos/Runner/GoogleService-Info.plist

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  google_sign_in: ^5.0.0
  mad2_db_dataobjects: ^1.1.0
  mad2_browsepage: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true

  image_path: "assets/appicon.png"
  min_sdk_android: 19 
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false


flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Medium.ttf
        - asset: assets/Montserrat-SemiBold.ttf  
        - asset: assets/Montserrat-Bold.ttf
        - asset: assets/Montserrat-ExtraBold.ttf         
    - family: Rubik_bold
      fonts:
        - asset: assets/Rubik-bold.ttf


  uses-material-design: true
  assets: 
   - assets/google_logo.png
   - assets/signinscreendesign.png
   - assets/DenLogo.jpg

