// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBolQI02sAbs6PY5AOZWSOTEDrre7uRMxA',
    appId: '1:621044417838:web:b4e74ee45ed4b1ba5c26bf',
    messagingSenderId: '621044417838',
    projectId: 'mad2-5df9e',
    authDomain: 'mad2-5df9e.firebaseapp.com',
    storageBucket: 'mad2-5df9e.appspot.com',
    measurementId: 'G-L240BQKSXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUoP9-qo9pH4m63phBD0A7WlYcus7Vd0M',
    appId: '1:621044417838:android:f3eedd9d94cac9215c26bf',
    messagingSenderId: '621044417838',
    projectId: 'mad2-5df9e',
    storageBucket: 'mad2-5df9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDsN1PAYjlcleaYer0oMttt97WfMJgPA',
    appId: '1:621044417838:ios:5c9d989821d967375c26bf',
    messagingSenderId: '621044417838',
    projectId: 'mad2-5df9e',
    storageBucket: 'mad2-5df9e.appspot.com',
    iosClientId:
        '621044417838-72171t6br2p83ljv6rdnhfcmt71eu3k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad2Login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDsN1PAYjlcleaYer0oMttt97WfMJgPA',
    appId: '1:621044417838:ios:5c9d989821d967375c26bf',
    messagingSenderId: '621044417838',
    projectId: 'mad2-5df9e',
    storageBucket: 'mad2-5df9e.appspot.com',
    iosClientId:
        '621044417838-72171t6br2p83ljv6rdnhfcmt71eu3k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mad2Login',
  );
}
